default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: dressme_development

test:
  <<: *default
  host: localhost
  database: dressme_test

production:
  <<: *default
  database: dressme_production
  username: dressme
  password: <%= ENV['DRESSME_DATABASE_PASSWORD'] %>
